name: in_app_purchase
description: A Flutter plugin for in-app purchases. Exposes APIs for making in-app purchases through the App Store and Google Play.
repository: https://github.com/flutter/plugins/tree/main/packages/in_app_purchase/in_app_purchase
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+in_app_purchase%22
version: 3.1.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: in_app_purchase_android
      ios:
        default_package: in_app_purchase_storekit
      macos:
        default_package: in_app_purchase_storekit

dependencies:
  flutter:
    sdk: flutter
  in_app_purchase_android:
    git:
      url: git@github.com:Genius-Systems-Nepal/flutter_plugins.git
      ref: query-product-subs
      path: packages/in_app_purchase/in_app_purchase_android
  in_app_purchase_platform_interface:
    git:
      url: git@github.com:Genius-Systems-Nepal/flutter_plugins.git
      ref: query-product-subs
      path: packages/in_app_purchase/in_app_purchase_platform_interface
  in_app_purchase_storekit:
    git:
      url: git@github.com:Genius-Systems-Nepal/flutter_plugins.git
      ref: query-product-subs
      path: packages/in_app_purchase/in_app_purchase_storekit

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  test: ^1.16.0

screenshots:
  - description: 'Example of in-app purchase on ios'
    path: doc/iap_ios.gif
  - description: 'Example of in-app purchase on android'
    path: doc/iap_android.gif
